name: Build fusee-rp2040 firmware

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential

      - name: Build firmware
        run: |
          mkdir build
          cd build
          cmake -G Ninja -DPICO_SDK_FETCH_FROM_GIT=on ..
          ninja
          
      - name: Upload firmware (.uf2)
        uses: actions/upload-artifact@v4
        with:
          name: fusee-rp2040-uf2
          path: build/fusee.uf2
