name: Build fusee-rp2040 firmware

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake ninja-build gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential

    - name: Build firmware
      run: |
        mkdir build
        cd build
        cmake -G Ninja ..
        ninja

    - name: Upload firmware (.uf2)
      uses: actions/upload-artifact@v3
      with:
        name: fusee-rp2040-uf2
        path: build/fusee.uf2
